add to makefiles to skip wget/git calls if files exist, make it OBS safe

diff --git a/applications/fax/Makefile b/applications/fax/Makefile
--- a/applications/fax/Makefile
+++ b/applications/fax/Makefile
@@ -12,6 +12,12 @@ comile-test: assets
 assets: $(PDF)
 
 $(PDF):
-	wget -qO $@ https://raw.githubusercontent.com/mathiasbynens/small/master/pdf.pdf
+	@if [ -f $@ ]; then \
+		echo "$@ already exists. Skipping download."; \
+	else \
+		echo "Downloading $@..."; \
+		wget -qO $@ https://raw.githubusercontent.com/mathiasbynens/small/master/pdf.pdf || { echo "Failed to fetch $@"; exit 1; }; \
+	fi
+
 
 include $(ROOT)/make/kz.mk
diff --git a/core/kazoo/Makefile b/core/kazoo/Makefile
--- a/core/kazoo/Makefile
+++ b/core/kazoo/Makefile
@@ -28,7 +28,13 @@ clean-generated:
 	$(if $(wildcard $(GEN_ERL)), @rm $(GEN_ERL))
 
 $(GEN_FILE):
-	wget -qO $@ $(GEN_URL)
+	@if [ -f $@ ]; then \
+		echo "$@ already exists. Skipping download."; \
+	else \
+		echo "Downloading $@..."; \
+		wget -qO $@ $(GEN_URL) || { echo "Failed to fetch $@"; exit 1; }; \
+	fi
+
 
 $(GEN_ERL): $(GEN_FILE) $(GEN_ERL_SRC)
 	@head -n `grep -n '%% GENERATED' $(GEN_ERL_SRC) | cut -d: -f1` $(GEN_ERL_SRC) > $(GEN_ERL)
diff --git a/core/kazoo_number_manager/Makefile b/core/kazoo_number_manager/Makefile
--- a/core/kazoo_number_manager/Makefile
+++ b/core/kazoo_number_manager/Makefile
@@ -43,7 +43,13 @@ clean-generated:
 	$(if $(wildcard $(ITU)), @rm $(ITU))
 
 $(ITU_FILE):
-	wget -qO $@ $(ITU_URL)
+	@if [ -f $@ ]; then \
+		echo "$@ already exists. Skipping download."; \
+	else \
+		echo "Downloading $@..."; \
+		wget -qO $@ $(ITU_URL) || { echo "Failed to fetch $@"; exit 1; }; \
+	fi
+
 
 $(ITU_SRC): $(ITU_FILE)
 
diff --git a/core/kazoo_proper/Makefile b/core/kazoo_proper/Makefile
--- a/core/kazoo_proper/Makefile
+++ b/core/kazoo_proper/Makefile
@@ -11,6 +11,11 @@ assets: $(MP3)
 
 $(MP3):
 	@mkdir -p $(shell dirname $(MP3))
-	wget -qO $@ https://raw.githubusercontent.com/mathiasbynens/small/master/mp3.mp3
+	@if [ -f $@ ]; then \
+		echo "$@ already exists. Skipping download."; \
+	else \
+		echo "Downloading $@..."; \
+		wget -qO $@ https://raw.githubusercontent.com/mathiasbynens/small/master/mp3.mp3 || { echo "Failed to fetch $@"; exit 1; }; \
+	fi
 
 include $(ROOT)/make/kz.mk
